import { generateObjectIDString, modelFactory } from "@turnkeyid/utils-ts";

export class ExampleModel {
  constructor(
    public id = generateObjectIDString(),
    public name: string,
    public description: string,
    public created_at = new Date(),
    public updated_at = new Date(),
  ) {}

  static factory = modelFactory(ExampleModel, { autoGeneratedProp: [`id`, `created_at`, `updated_at`] })
}

export class ExampleModelPublic {
  constructor(
    public name: string,
    public description: string,
  ) {}

  static factory = modelFactory(ExampleModelPublic)
}